services:

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: helprly
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # postgres_test:
  #   image: postgres:latest
  #   container_name: postgres_test
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: helprly_test
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - postgres-test-data:/var/lib/postgresql/data

  helprly:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: helprly
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres:password@localhost:5432/helprly
    restart: unless-stopped

volumes:
  postgres-data:
  # postgres-test-data: